@startuml "zeta-workload-identity-federation"

autonumber "(00)"
skinparam defaultFontSize 10
skinparam defaultFontName Helvetica
skinparam DefaultMonospacedFontName Courier
skinparam lengthAdjust none
skinparam sequenceReferenceBackgroundColor White
skinparam SequenceReferenceFontSize 12

!pragma teoz true

box "Kubernetes Cluster" #GhostWhite
  participant "Client Workload" as Client
  participant "Kubernetes IDP" as K8sIDP
end box

box "Anbieter" #TECHNOLOGY
  box "ZETA Guard" #SandyBrown
    participant "ZETA Guard\nAuthorization Server (STS)" as ZetaSTS
    participant "PEP\nHTTP Proxy" as HP
    participant "Policy Engine\n(OPA)" as OPA
  end box
    box TI 2.0 Dienst #DarkSeaGreen
        participant "Resource Server" as ResourceServer
    end box
end box

activate Client
Client -> K8sIDP++: Fordert ID-Token an
K8sIDP --> Client--: ID-Token

Client -> ZetaSTS++: Fordert Access-Token an\n(Token Exchange mit ID-Token)
ZetaSTS -> K8sIDP++:  GET /openid/v1/jwks
K8sIDP --> ZetaSTS--: JWKS
ZetaSTS -> ZetaSTS: Validiert ID-Token\n(Signatur, Ablauf, etc.)
alt Erfolgreiche Validierung
  ZetaSTS -> OPA++: Entscheidungsanfrage (issuer uri, etc.)
  OPA --> ZetaSTS--: Ergebnis
else Fehlgeschlagene Validierung
  ZetaSTS --> Client: Fehler 403 Forbidden
end
alt Erfolgreiche Autorisierung
    ZetaSTS --> Client: Access-Token
else Fehlgeschlagene Autorisierung
    ZetaSTS --> Client--: Fehler 403 Forbidden
end

Client -> HP++: Anfrage mit Access-Token
HP -> HP: Validiert Access-Token
 alt Erfolgreiche Validierung
  HP -> ResourceServer++: Weiterleitung der Anfrage mit Access-Token
  ResourceServer --> HP--: Antwort
  HP --> Client: Antwort
 else Fehlgeschlagene Validierung
    HP --> Client--: Fehler 401 Unauthorized
 end

deactivate Client
@enduml