# Platform specific product id for Android Apps
$schema: "http://json-schema.org/draft-07/schema#"
title: Android Product ID
description: The product identifier for Android apps
type: object
properties:
  platform:
    type: string
    const: "android"
  namespace:
    type: string
    const: "android_app"
  package_name:
    type: string
  sha256_cert_fingerprints:
    type: array
    items:
      type: string
required:
  - namespace
  - package_name
  - sha256_cert_fingerprints
