# Plattformspezifische Produkt-ID für Windows Apps
type: object
properties:
  store_id:
    type: string
    description: The Store ID for the Windows app.
  package_family_name:
    type: string
    description: The Package Family Name for the Windows app.
