# Platform specific product id for Apple Apps (iOS, macOS, iPadOS, watchOS, tvOS, etc.)
$schema: "http://json-schema.org/draft-07/schema#"
title: Apple Product ID
description: The product identifier for Apple apps
type: object
properties:
  platform:
    type: string
    const: "apple"
  platform_type:
    type: string
  app_bundle_ids:
    type: array
    items:
      type: string
required:
  - app_bundle_ids
  - platform_type
