@startuml "Abb-ZETA-Zugriff-auf-RS-ohne-ASL"
!include ../puml-layout.txt


Actor User
box "Primärsystem" PRIMAERSYSTEM_COLOR
  participant FC as "Fach-Client" <<provider>>
  participant Client as "ZETA Client" <<zeta>>
end box

box "Anbieter" PROVIDER_COLOR
  box "ZETA Guard" ZETA_GUARD_COLOR
    participant HP as "PEP\nHTTP Proxy" <<zeta>>
  end box
  participant RS as "Resource\nServer" <<provider>>
end box

User -> FC ++ : User wants to\naccess resource\non Resource Server
FC -> Client ++ : GET /resource

note over Client, HP: **Vorbedingung:**\nDer ZETA Client hat ein gültiges Access Token für den Zugriff auf den Resource Server.

Client -> Client: Create DPoP Proof for RS

Client -> HP++: GET /resource\n\
    Authorization: DPoP ... (Accesss token)\n\
    DPoP: ... (DPoP token)
HP -> HP: verify Access Token and DPoP Proof
HP -> RS ++ : forward GET /resource\n\
with header and\nPEP header as JSON
RS -> RS: Create Response
RS --> HP -- : 200 OK, Response
HP --> Client -- : 200 OK, Response

Client --> FC -- : 200 OK, Response
FC --> User -- : Response

@enduml