@startuml "key-preparation"
!include ../layout.puml


box "Apple Device (macOS, iOS, iPadOS)" MOBILE_COLOR
  participant "Secure Enclave" as SE LEI_COMPONENT_COLOR
  participant "OS (iOS / iPadOS)" as AppleOS LEI_COMPONENT_COLOR
  participant "ZETA Client" as Client <<zeta>>
end box


alt macOS, iOS, iPadOS

    Client++
    note left of Client: App nutzt native Apple-Frameworks.
    
    Client -> AppleOS++: DCAppAttest.generateAssertion(keyId_AK, hash_puk_client_sig)
    AppleOS -> SE++: Signiere Hash
    SE --> AppleOS--: ECDSA Signatur
    AppleOS --> Client--: apple_assertion_object
    Client--

else Software Attestation (Fallback)
    note left of Client: Keine Hardware-Bindung.\nApp oder Client erstellt prk_client_sig selbst.
end

@enduml