@startuml "key-preparation"
!include ../layout.puml


    box "Device" DEVICE_COLOR
      participant "TEE / StrongBox" as StrongBox
      participant "Android OS" as AndroidOS
      box "App" PRIMAERSYSTEM_COLOR
        participant "ZETA Client" as Client <<zeta>>
      end box
    end box

    Client++
    AndroidOS++
    note left of Client: App nutzt nativen Android KeyStore.
    
    Client -> AndroidOS: KeyStore.generateKey(\nAttestationChallenge = hash_puk_client_sig)
    AndroidOS -> StrongBox++: Erzeuge Key & Chain
    StrongBox --> AndroidOS--: Zertifikatskette
    AndroidOS --> Client: android_key_attestation_certificate_chain
    
    Client -> AndroidOS: Signature.sign(KeyStore.getKey(Alias_AK), hash_puk_client_sig)
    AndroidOS -> StrongBox++: Signiere Hash
    StrongBox --> AndroidOS--: ECDSA Signatur
    AndroidOS --> Client--: signed_hash_puk_client_sig
    Client--

@enduml