@startuml "client-installation"
autonumber "(00)"
skinparam defaultFontSize 10
skinparam defaultFontName Helvetica
skinparam DefaultMonospacedFontName Courier
skinparam lengthAdjust none
skinparam sequenceReferenceBackgroundColor White
skinparam SequenceReferenceFontSize 12
skinparam sequenceMessageAlign left
hide stereotype

' Box colors
!define ZETA_GUARD_COLOR #FFF3E5
!define LEI_COLOR #GhostWhite
!define LEI_COMPONENT_COLOR #E4E4F4
!define PRIMAERSYSTEM_COLOR #Lavender
!define PROVIDER_COLOR #EDFDEC
!define DEVICE_COLOR #fefcff

' Participant colors
<style>
sequenceDiagram {
  participant {
    .zeta {
      BackgroundColor #FFE6CC
      LineColor #D79B00
    }
    .provider {
      BackgroundColor #D5E8D4
      LineColor #82B366
    }
  }
  lifeline {
    BackgroundColor White
    LineColor Black
  }
}
</style>

' title Client Installation & Baseline-Etablierung

!pragma teoz true

box "Device" DEVICE_COLOR
  participant "Secure Enclave" as SE LEI_COMPONENT_COLOR
  participant "OS (macOS, iOS, iPadOS)" as AppleOS LEI_COMPONENT_COLOR
  box "App" PRIMAERSYSTEM_COLOR
    participant "ZETA Client" as Client <<zeta>>
  end box
end box

Client++
AppleOS++
Client --> Client: Installation (User Space)

alt Secure Enclave
    Client -> AppleOS: SecKeyCreateRandomKey\n(für PrK.Client.Sig, PuK.Client.Sig in SE)
    AppleOS -> SE++: Generiere Schlüssel (Client.Sig)
    SE --> AppleOS--: keyId (Referenz für PrK.Client.Sig)
    AppleOS --> Client: keyId (Referenz für PrK.Client.Sig)
else Fallback
    Client -> Client: Generiere PrK.Client.Sig,\nPuK.Client.Sig
end

@enduml