@startuml "token-exchange-with-attestation"
autonumber "(00)"
skinparam defaultFontSize 10
skinparam defaultFontName Helvetica
skinparam DefaultMonospacedFontName Courier
skinparam lengthAdjust none
skinparam sequenceReferenceBackgroundColor White
skinparam SequenceReferenceFontSize 12
skinparam sequenceMessageAlign left
hide stereotype

' Box colors
!define ZETA_GUARD_COLOR #FFF3E5
!define LEI_COLOR #GhostWhite
!define LEI_COMPONENT_COLOR #E4E4F4
!define PRIMAERSYSTEM_COLOR #Lavender
!define PROVIDER_COLOR #EDFDEC

' Participant colors
<style>
sequenceDiagram {
  participant {
    .zeta {
      BackgroundColor #FFE6CC
      LineColor #D79B00
    }
    .provider {
      BackgroundColor #D5E8D4
      LineColor #82B366
    }
  }
  lifeline {
    BackgroundColor White
    LineColor Black
  }
}
</style>

' title Token Exchange with Attestation

!pragma teoz true

box "LEI" LEI_COLOR
  participant Konnektor as "Konnektor or\nTI-Gateway" LEI_COMPONENT_COLOR
  participant SMB as "SM(C)-B" LEI_COMPONENT_COLOR
  box "Primärsystem" PRIMAERSYSTEM_COLOR
    participant Client as "ZETA Client" <<zeta>>
  end box
end box

box "Anbieter TI 2.0 Dienst" PROVIDER_COLOR
  box "ZETA Guard" ZETA_GUARD_COLOR
    participant AuthS as "PDP\nAuthorization Server" <<zeta>>
    participant OPA as "PDP\nPolicy Engine" <<zeta>>
  end box
end box

Client++
Client -> Client: Generiere subject_token

group Sign Subject Token with SM(C)-B
    Client -> Konnektor ++
    Konnektor --> Client -- : 
end

Client -> Client : Create DPoP Key Pair (PrK.DPoP.Sig, PuK.DPoP.Sig)
note right: Session-based Key Pair for DPoP binding.

Client -> Client : Create DPoP Proof (with Nonce from AuthS)
Client -> AuthS++: POST /token dpop: dpop_proof\n{client_assertion (JWT, PrK.Client.Sig signiert),\nsubject_token (SMC-B signiert, inkl. Nonce),\n[Evidence]}

AuthS -> AuthS: Validate Request (Client Assertion, DPoP Proof,\nSubject Token, Nonce and Key bindings from DCR)        
alt TPM Attestation (Windows / Linux)
    AuthS -> AuthS: Verifiziere Hardware-Signatur (Quote) gegen extrahierte Nonce\nPCR-Replay via Event Log
else macOS Attestation (Secure Enclave)
    AuthS -> AuthS: Prüfe Signaturen und counter (Replay-Schutz)
end
alt Validation successful
    AuthS -> AuthS: Policy Engine Input erstellen
    AuthS -> OPA++: POST /v1/data/authz {Policy Engine Input}
    OPA --> AuthS--: Policy Decision

    alt Policy Decision allow
        AuthS -> AuthS: Create Token (Access Token, Refresh Token)
        alt Hardware Attestation  (TPM / SE)
            AuthS -> AuthS: Create ZETA Guard Attestation Token (zg_att_token)
            AuthS --> Client: 200 OK {Access Token, Refresh Token, zg_att_token}
        else Software Attestation (Fallback)
            AuthS --> Client: 200 OK {Access Token, Refresh Token}
        end
    else Policy Decision deny
        AuthS --> Client--: 403 Forbidden
    end
else Validation fehlerhaft
    AuthS --> Client--: 403 Forbidden
end

@enduml